services:
  - type: web
    name: nhl-discord-bot
    env: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    healthCheckPath: /health
    envVars:
      - key: NODE_ENV
        value: production
      - key: DISCORD_TOKEN
        sync: false  # You'll set this manually in Render dashboard
      - key: APP_ID
        sync: false  # You'll set this manually in Render dashboard
      - key: PUBLIC_KEY
        sync: false  # You'll set this manually in Render dashboard